name: Build

on:
  push:
    branches:
    - 'main'
  pull_request:
    types: [opened, synchronize, reopened]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: [ "3.8", "3.11", "3.12" ]

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Base Setup
      uses: jupyterlab/maintainer-tools/.github/actions/base-setup@v1

    - name: Install dependencies
      run: python -m pip install -U "jupyterlab>=4.0.0,<5" check-manifest pyunicore pytest pytest-mock pytest-cov

    - name: Lint the extension
      run: |
        set -eux
        jlpm
        jlpm run lint:check

    - name: Test the extension
      run: |
        set -eux
        jlpm run test

    - name: Build the extension
      env:
        CLB_AUTH: 'TEST_TOKEN'
      run: |
        set -eux
        jlpm
        jlpm run eslint:check
        python -m pip install .[test]

        pytest -vv -r ap tvbextunicore
        jupyter server extension list
        jupyter server extension list 2>&1 | grep -ie "tvbextunicore.*OK"

        jupyter labextension list
        jupyter labextension list 2>&1 | grep -ie "tvb-ext-unicore.*OK"
        python -m jupyterlab.browser_check

        check-manifest -v

        pip install build
        python -m build --sdist
        cp dist/*.tar.gz myextension.tar.gz
        pip uninstall -y "tvb-ext-unicore" jupyterlab
        rm -rf myextension

    - name: Run tests
      run: |
        pytest tvbextunicore -r ap

    - name: Compute coverage
      run: |
        pytest -v  --cov --cov-report=xml

    - name: Run JS tests
      run: |
        yarn test

    - name: Compute JS coverage
      run: |
        yarn test --coverage

    - name: SonarCloud Scan
      uses: sonarsource/sonarcloud-github-action@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

    - uses: actions/upload-artifact@v3
      with:
        name: myextension-sdist
        path: myextension.tar.gz

  test_isolated:
    needs: build
    runs-on: ubuntu-latest

    steps:
    - name: Install Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
        architecture: 'x64'
    - uses: actions/download-artifact@v4
      with:
        name: extension-artifacts
    - name: Install and Test
      run: |
        set -eux
        # Remove NodeJS, twice to take care of system and locally installed node versions.
        sudo rm -rf $(which node)
        sudo rm -rf $(which node)

        pip install "jupyterlab>=4.0.0,<5" tvbextunicore*.whl


        jupyter server extension list
        jupyter server extension list 2>&1 | grep -ie "tvbextunicore.*OK"

        jupyter labextension list
        jupyter labextension list 2>&1 | grep -ie "tvb-ext-unicore.*OK"
        python -m jupyterlab.browser_check --no-browser-test
